specVersion: 1.0.0
name: SubQuery Dictionary - Westend
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: >-
  A SubQuery Dictionary Project that provides increased indexing speed to all
  projects
repository: 'https://github.com/bgodlin/sora-subquery-dictionary'
schema:
  file: ./schema.graphql
network:
  chainId: '0xfd8ccfd5c41eef0dd6fb9874807c9f90e677dfae806f3faec83f9e10da436cea'
  endpoint: 'wss://ws.framenode-2.s2.dev.sora2.soramitsu.co.jp'
  chaintypes:
    file: ./types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
